# Default configuration for Spotify Engine data generation

# User behavior patterns
user_types:
  distribution:
    casual: 0.5
    regular: 0.35
    power: 0.15

  activity_levels:
    casual: [0.1, 0.3] # min, max activity multiplier
    regular: [0.3, 0.7]
    power: [0.7, 1.0]

  genre_preferences:
    casual: [1, 3] # min, max number of preferred genres
    regular: [2, 5]
    power: [3, 8]

# Session configuration
sessions:
  # Session length distribution (songs per session)
  length_weights:
    1: 0.2
    3: 0.3
    5: 0.25
    10: 0.15
    20: 0.1

  # Listening behavior weights
  behavior_weights:
    full: 0.4 # Listen to full song
    skip: 0.2 # Skip early
    partial: 0.4 # Listen to partial song

  # Continuity preferences
  same_artist_probability: 0.4
  weekday_preference_probability: 0.8
  weekend_preference_probability: 0.5

# Time patterns - hourly listening weights (24 hours)
time_patterns:
  hourly_weights:
    - 0.3 # 00:00
    - 0.3 # 01:00
    - 0.3 # 02:00
    - 0.3 # 03:00
    - 0.4 # 04:00
    - 0.6 # 05:00
    - 0.8 # 06:00
    - 1.0 # 07:00 (morning commute)
    - 0.9 # 08:00
    - 0.5 # 09:00
    - 0.4 # 10:00
    - 0.4 # 11:00
    - 0.5 # 12:00 (lunch)
    - 0.6 # 13:00
    - 0.7 # 14:00
    - 0.8 # 15:00
    - 0.9 # 16:00
    - 1.0 # 17:00 (evening commute)
    - 1.0 # 18:00
    - 1.0 # 19:00
    - 0.9 # 20:00
    - 0.8 # 21:00
    - 0.6 # 22:00
    - 0.4 # 23:00

# Artist and song configuration
content:
  artist_popularity_alpha: 1.5 # Pareto distribution parameter

  artist_genre_distribution:
    1: 0.5 # 50% of artists have 1 genre
    2: 0.35 # 35% have 2 genres
    3: 0.15 # 15% have 3 genres

  song_duration:
    min_ms: 30000 # 30 seconds
    max_ms: 600000 # 10 minutes

# Playback thresholds
playback:
  skip_threshold_ms: 30000 # Songs < 30s are considered skips
  completion_threshold_ratio: 0.8 # Songs played >= 80% are complete

# Data quality settings
validation:
  min_sessions_per_user: 1
  max_skip_rate: 0.5
  min_completion_rate: 0.2
