# Configuration for weekend-heavy listening patterns

# User behavior patterns
user_types:
  distribution:
    casual: 0.3 # Fewer casual users
    regular: 0.4 # More regular users
    power: 0.3 # More power users

  activity_levels:
    casual: [0.2, 0.4] # Higher activity
    regular: [0.4, 0.8]
    power: [0.8, 1.0]

  genre_preferences:
    casual: [2, 4] # More diverse genres
    regular: [3, 6]
    power: [4, 10]

# Session configuration
sessions:
  # Longer sessions on weekends
  length_weights:
    1: 0.1 # Fewer single-song sessions
    3: 0.2
    5: 0.25
    10: 0.25 # More medium sessions
    20: 0.2 # More long sessions

  # Less skipping on weekends
  behavior_weights:
    full: 0.5 # More full listens
    skip: 0.1 # Less skipping
    partial: 0.4

  # Weekend-focused preferences
  same_artist_probability: 0.5 # More artist continuity
  weekday_preference_probability: 0.6 # Less rigid on weekdays
  weekend_preference_probability: 0.3 # More exploration on weekends

# Time patterns - weekend-heavy
time_patterns:
  hourly_weights:
    - 0.6 # 00:00 - More late night weekend
    - 0.5 # 01:00
    - 0.4 # 02:00
    - 0.3 # 03:00
    - 0.3 # 04:00
    - 0.3 # 05:00
    - 0.4 # 06:00
    - 0.5 # 07:00
    - 0.6 # 08:00
    - 0.8 # 09:00 - Weekend mornings
    - 0.9 # 10:00
    - 1.0 # 11:00
    - 1.0 # 12:00 - Weekend lunch
    - 1.0 # 13:00
    - 0.9 # 14:00
    - 0.9 # 15:00
    - 0.9 # 16:00
    - 1.0 # 17:00
    - 1.0 # 18:00 - Weekend evening
    - 1.0 # 19:00
    - 1.0 # 20:00
    - 0.9 # 21:00
    - 0.8 # 22:00
    - 0.7 # 23:00

# Content settings remain the same
content:
  artist_popularity_alpha: 1.5
  artist_genre_distribution:
    1: 0.5
    2: 0.35
    3: 0.15
  song_duration:
    min_ms: 30000
    max_ms: 600000

# Playback thresholds
playback:
  skip_threshold_ms: 30000
  completion_threshold_ratio: 0.8
